### ISSUE TITLE
Is it possible to use this for No-SQL(Mongo)?

### ISSUE THREAD

**Issue by vrmsreddy** [spring-projects/spring-data-envers#100]
Spring data envers is a common for mongo,JPA..
I mean CrudRepository

**Comment by schauder** [comment]
From the README:

> This project is an extension of the Spring Data JPA project to allow access to entity revisions managed by Hibernate Envers.

So it is not just limited to JPA, but to Hibernate. You can't use it with MongoDB.

Depending on what you actually want to do the event mechanism might be helpful: https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#core.domain-events

**Comment by vrmsreddy** [comment]
Thanks
