### ISSUE TITLE
is there a good example for Spring data Envers. I found a few, but I am not very clear on how to use it. 

### ISSUE THREAD

**Issue by ap1256** [spring-projects/spring-data-envers#101]
I am using temporal table feature in DB2. I was able to create basic CRUD operations using spring data jpa. But I have need to show the audit log in the UI. so I was looking at using Spring Data Envers. I extended my Repository from RevisionRepository. 
FindRevision is giving me following error - DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=PROVDB01.REVINFO, DRIVER=4.14.113
It is looking for revinfo column.

**Comment by schauder** [comment]
Sounds like you didn't create the Audit tables as required by Envers. If this is really the problem you should check the [Envers documentation](https://docs.jboss.org/envers/docs/). 

[Spring Data Envers comes with an integration test](https://github.com/spring-projects/spring-data-envers/blob/1383d815e674e745a4a22d835038ee1393ee2b5a/src/test/java/org/springframework/data/envers/repository/support/RepositoryIntegrationTests.java#L49) which makes for a reasonable good example:.
