### ISSUE TITLE
findRevision(ID, N) returns partially filled entities

### ISSUE THREAD

**Issue by evilchewits** [spring-projects/spring-data-envers#103]
The comment for the method definition of [`findRevision(ID, N)`](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/repository/history/RevisionRepository.java) in _spring-data-commons_ says that it should return **the entity with the given ID in the given revision number**.

So if I annotate my entity with `@Audited` skipping some fields with `@NotAudited`:

```
@Entity
@Audited
public class SimpleEntity {
  @Id
  @GeneratedValue
  private Integer id;

  private String data1;

  @NotAudited
  private String data2;
  ...
}
```

I expect that it returns the full entity (!) fetching audited fields from SimpleEntity_AUD and the rest from SimpleEntity table. That's not the case, in fact. The `findRevision(ID, N)` implementation returns `null` for all `@NotAudited` fields.

I understand the reason: `AuditReader.find(...)` method called from `getEntityForRevision(...)` is not obliged to return the full entity by specification:

```
/**
 * Find an entity by primary key at the given revision.
 * <...>
 * @return The found entity instance at the given revision (its properties may be partially filled
 *         if not all properties are audited) or null, if an entity with that id didn't exist at that
 *         revision.
 * <...>
 */
<T> T find(Class<T> cls, Object primaryKey, Number revision) throws
    IllegalArgumentException, NotAuditedException, IllegalStateException;
```

But I still consider this a bug in _spring-data-envers_. In my understanding, the right implementation should return **the entity**, not the **partially filled entity**.

P.S. I guesss the same applies to `findRevisions(ID)`...

Alexander

**Comment by schauder** [comment]
While I understand that this might be what someone wants, I doubt this is what we should do as a default.

It would create an entity that is a mixture of **two** entities states that really existed at some point in time, which is a weird thing to have in itself.

And really `@NotAudited` means you don't want this attribute audited, why would you expect it to turn up in an audited entity?

So if at all I'd consider it a documentation issue for commons and we probably accept an issue and PR for that. But really it is just the basic behavior of Envers and we don't normally explicitly document this kind of stuff.
