### ISSUE TITLE
It must use HibernateJpaVendorAdapter?

### ISSUE THREAD

**Issue by long187** [spring-projects/spring-data-envers#108]
org.eclipse.persistence.jpa.PersistenceProvider is not work.

`java.lang.StackOverflowError
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.getDelegate(EntityManagerImpl.java:1270)
	at org.hibernate.envers.AuditReaderFactory.get(AuditReaderFactory.java:62)`

**Comment by schauder** [comment]
Please add more context about what actions/setup results in the error.

**Comment by long187** [comment]
In our project, We use org.eclipse.persistence.jpa.PersistenceProvider instead of hibernateProvider, so envers is not work.

**Comment by schauder** [comment]
Envers is a Hibernate feature. So yes, Spring Data Envers will only work with Hibernate.

**Comment by long187** [comment]
thks
