### ISSUE TITLE
RevisionMetadata cannot handle RevisionTimestamp in TIMESTAMP format

### ISSUE THREAD

**Issue by stefanzilske** [spring-projects/spring-data-envers#135]
Hi folks,

I started using Hibernate Envers natively and created my own RevisonInfo and REVINFO table. I used TIMESTAMP as data type for the RevisionTimestamp and mapped it to java.util.Date, which is fine for Hibernate.

Now we are starting to use spring-data-envers and run into the following issue:

RevisionMetadata expects the RevisionTimestamp to be either an Instant, LocalDateTime Long, while Hibernate supports only Long, java.util.Date or java.sql.Date.

I could switch to long, but I would prefer to keep a readable format in the database.

Is there any way out of this? I wonder why spring-data-envers, which wraps Hibernate Envers, is supporting different types.

Cheers,
Stefan

**Comment by olivergierke** [comment]
If you map it to a `java.util.Date`, shouldn't you be able to adapt it to an `Instant`?

**Comment by olivergierke** [comment]
Oh, wait. Now I get you. I guess the relevant parts are missing in Spring Data Commons' `AnnotationRevisionMetadata.convertToInstant(…)`. I wouldn't mind to see a PR that adds the necessary if-clause to convert from `Date` or `Timestamp` right away. However, we'd have to track this in Spring Data Commons.

**Comment by olivergierke** [comment]
I've filed [DATACMNS-1384](https://jira.spring.io/browse/DATACMNS-1384). Looks pretty straight forward, I'll get right to it.

**Comment by stefanzilske** [comment]
@olivergierke we have tried the latest snapshots and it works fine. Thank you for the quick reaction!

**Comment by olivergierke** [comment]
Awesome, thanks for confirming.

**Comment by arvera** [comment]
Is there documetation that explains how to achieve the transformation?

**Comment by arvera** [comment]
> Is there documetation that explains how to achieve the transformation?

Well I figure it out and it might worth to add it to some documentation. This is what I did for Derby:

My class looks like: 

```
public class MyRevisionInfo implements Serializable{
...	
   @RevisionTimestamp
   @Column (name="REVTSTMP")
   private Instant timestamp;
...
   @Transient
   public Date getRevisionDate() {
		 return new Date(timestamp.toEpochMilli());
   }
   
   public Instant getTimestamp() {
        return timestamp;
   }

   public void setTimestamp(Instant timestamp) {
        this.timestamp = timestamp;
   }

```

 and my ddl looks like:
 ```
      create table REVINFO (
        REVISION bigint generated by default as identity,
        REVTSTMP timestamp,
        USERNAME varchar(255),
        primary key (REVISION)
    );
```

**Comment by ngmip** [comment]
@arvera I'm trying to do just what you show here 
``` java
   @RevisionTimestamp
   @Column (name="REVTSTMP")
   private Instant timestamp;
```
yet my application does not boot because `The field annotated with @RevisionTimestamp must be of type long, Long, java.util.Date or java.sql.Date`

Is there anything else I should configure somewhere (spring-boot 2.7.18 with spring-data-envers dependency) ?
