### ISSUE TITLE
Release 1.1.16 (Ingalls SR16)

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-envers#136]

**Comment by starrybleu** [comment]
Can you consider to migrate commits regarding the issue of #21 for 1.1.16?

**Comment by schauder** [comment]
@starrybleu could you create a separate issue for that. It will increase the chance that I'll notice and consider it when I have time.

**Comment by starrybleu** [comment]
Sure, I will create a new issue. Thank you for your time.
