### ISSUE TITLE
Support finding deleted entity's revisions for 1.1.x.

### ISSUE THREAD

**Issue by starrybleu** [spring-projects/spring-data-envers#139]
There is a known issue for finding revisions of deleted entity.

For 2.0.x, this issue was fixed from #21.

Now I need a fix for 1.1.x because my team is still using spring-boot 1.5.x corresponding spring-data-envers 1.1.x.

**Comment by starrybleu** [comment]
I have already committed for this. Please see #140.

**Comment by olivergierke** [comment]
We don't backport new features into branches in maintenance mode.

**Comment by starrybleu** [comment]
I think this is a bug, not a new feature, though. I cannot understand revisions of deleted entity cannot be retrieved as expected. Anyway, thank you for quick response.
