### ISSUE TITLE
Better extensibility

### ISSUE THREAD

**Issue by pfink** [spring-projects/spring-data-envers#17]
At the moment, if one wants to combine RevisionRepository's with own custom functionality for all repositories, he has to fully rewrite the factory bean (with much copy&paste) which is about a quarter of the whole code of this project!

Simple measures to improve extensibility:
- Make RevisionRepositoryFactory public
- Provide protected getters for relevant properties in the factory(-bean)

**Comment by duclad** [comment]
+1

**Comment by manios** [comment]
+1

**Comment by dquintela** [comment]
Does my #82 help ?

**Comment by mkoppanen** [comment]
👍

**Comment by gregturn** [comment]
Closing due to lack of interest.
