### ISSUE TITLE
load revisions after deleted entity

### ISSUE THREAD

**Issue by ch0uCas** [spring-projects/spring-data-envers#21]
simple sample : Entity A
- insert A , modify A
  findByRevision(...) returns 2 entries
- delete A
  findRevision raised an exception: because in the class org.springframework.data.history.Revision entity is null

how can i load all audited values of A.

**Comment by mcnaggets** [comment]
any progress?

**Comment by razorvind** [comment]
here is what I have now for deleted entity using findRevisions:
Method threw 'org.springframework.dao.InvalidDataAccessApiUsageException' exception.
Detailed message: [Assertion failed] - this argument is required; it must not be null

Are you going to fix this?

**Comment by mateuszwinnicki** [comment]
Hi, any progress on that?

**Comment by vbaidak** [comment]
+1

**Comment by mateuszwinnicki** [comment]
In fact that problem is not in spring-data-envers but rather in spring-data

**Comment by hgschwibbe** [comment]
+2

**Comment by hgschwibbe** [comment]
Auditing deleted entries is one of the most important feature of Hibernate Envers. Without that feature this framework makes no sense, you can use the default Spring Data auditing mechanism instead.

**Comment by hgschwibbe** [comment]
The null check is in Spring Data Commons:
`	public Revision(RevisionMetadata<N> metadata, T entity) {

		Assert.notNull(metadata);
		Assert.notNull(entity);

		this.metadata = metadata;
		this.entity = entity;
	}
`
This null check applies well to Spring Data's default auditing, but not for Hibernate Envers. In Hibernate Envers we expect a null entry for a delete revision.

**Comment by drenda** [comment]
+1

**Comment by lkerck** [comment]
+1

**Comment by querqueq** [comment]
:+1:

**Comment by Alwaysgone** [comment]
👍

**Comment by schauder** [comment]
Fixed for upcoming 2.1.x and 2.0.x

**Comment by davipc** [comment]
Good afternoon,

Is this fix in place yet? 
I'm trying to use Spring Data Envers in a project at my company, but ended up falling into the same problem.

**Comment by schauder** [comment]
Yes, it is in the 2.0.3 release and in the 2.1 M1

**Comment by starrybleu** [comment]
Since I’m using spring boot 1.5.x, can I use fixed version correspondingly? I tried, but failed. Is there a fixed version for 1.5.x?
