### ISSUE TITLE
RevisionType always Unknown in RevisionMetadata

### ISSUE THREAD

**Issue by SBylemans** [spring-projects/spring-data-envers#215]
**Problem**
RevisionType retrieved from revision metadata is always unknown.

**Cause**
[`EnversRevisionRepositoryImpl.getRevisionMetadata()`](https://github.com/spring-projects/spring-data-envers/blob/7ef1103ceec365e7b70d97e359eec0620986839e/src/main/java/org/springframework/data/envers/repository/support/EnversRevisionRepositoryImpl.java#L235) always returns an [AnnotationRevisionMetadata](https://github.com/spring-projects/spring-data-commons/blob/664e661783a78d52c82af8663f2f2115222c828b/src/main/java/org/springframework/data/history/AnnotationRevisionMetadata.java) object with an old constructor which passes UNKNOWN type to the new constructor in [AnnotationRevisionMetadata](https://github.com/spring-projects/spring-data-commons/blob/664e661783a78d52c82af8663f2f2115222c828b/src/main/java/org/springframework/data/history/AnnotationRevisionMetadata.java#L70).

**Solution**
Use of new constructor in [AnnotationRevisionMetadata](https://github.com/spring-projects/spring-data-commons/blob/664e661783a78d52c82af8663f2f2115222c828b/src/main/java/org/springframework/data/history/AnnotationRevisionMetadata.java#L70) in [EnversRevisionRepositoryImpl.java](https://github.com/spring-projects/spring-data-envers/blob/7ef1103ceec365e7b70d97e359eec0620986839e/src/main/java/org/springframework/data/envers/repository/support/EnversRevisionRepositoryImpl.java#L235) `getRevisionMetadata`.

[**EnversRevisionRepositoryImpl.java**](https://github.com/spring-projects/spring-data-envers/blob/7ef1103ceec365e7b70d97e359eec0620986839e/src/main/java/org/springframework/data/envers/repository/support/EnversRevisionRepositoryImpl.java#L235)
```
	/**
	 * Returns the {@link RevisionMetadata} wrapper depending on the type of the given object.
	 *
	 * @param object
	 * @return
	 */
	private RevisionMetadata<?> getRevisionMetadata(Object object) {

		return object instanceof DefaultRevisionEntity //
				? new DefaultRevisionMetadata((DefaultRevisionEntity) object) //
				: new AnnotationRevisionMetadata<N>(object, RevisionNumber.class, RevisionTimestamp.class);
	}
```

[**AnnotationRevisionMetadata.java -> old constructor**](https://github.com/spring-projects/spring-data-commons/blob/664e661783a78d52c82af8663f2f2115222c828b/src/main/java/org/springframework/data/history/AnnotationRevisionMetadata.java#L54)
```
	/**
	 * Creates a new {@link AnnotationRevisionMetadata} inspecting the given entity for the given annotations. If no
	 * annotations will be provided these values will not be looked up from the entity and return {@literal null}. The
	 * revisionType will be set to {@literal unknown}
	 *
	 * @param entity must not be {@literal null}.
	 * @param revisionNumberAnnotation must not be {@literal null}.
	 * @param revisionTimeStampAnnotation must not be {@literal null}.
	 */
	public AnnotationRevisionMetadata(Object entity, Class<? extends Annotation> revisionNumberAnnotation,
			Class<? extends Annotation> revisionTimeStampAnnotation) {

		this(entity, revisionNumberAnnotation, revisionTimeStampAnnotation, RevisionType.UNKNOWN);
	}
```

[**AnnotationRevisionMetadata.java -> new constructor**](https://github.com/spring-projects/spring-data-commons/blob/664e661783a78d52c82af8663f2f2115222c828b/src/main/java/org/springframework/data/history/AnnotationRevisionMetadata.java#L70)
```
	/**
	 * Creates a new {@link AnnotationRevisionMetadata} inspecting the given entity for the given annotations. If no
	 * annotations will be provided these values will not be looked up from the entity and return {@literal null}.
	 *
	 * @param entity must not be {@literal null}.
	 * @param revisionNumberAnnotation must not be {@literal null}.
	 * @param revisionTimeStampAnnotation must not be {@literal null}.
	 * @param revisionType must not be {@literal null}.
	 * @since 2.2.0
	 */
	public AnnotationRevisionMetadata(Object entity, Class<? extends Annotation> revisionNumberAnnotation,
			Class<? extends Annotation> revisionTimeStampAnnotation, RevisionType revisionType) {

		Assert.notNull(entity, "Entity must not be null!");
		Assert.notNull(revisionNumberAnnotation, "Revision number annotation must not be null!");
		Assert.notNull(revisionTimeStampAnnotation, "Revision time stamp annotation must not be null!");
		Assert.notNull(revisionType, "Revision Type must not be null!");

		this.entity = entity;
		this.revisionNumber = detectAnnotation(entity, revisionNumberAnnotation);
		this.revisionDate = detectAnnotation(entity, revisionTimeStampAnnotation);
		this.revisionType = revisionType;
	}
```

**Comment by schauder** [comment]
Thanks for finding and reporting this.

Since you analysed this rather detailed, do you care to provide a PR?

**Comment by SBylemans** [comment]
This could be resolved in [pull request 195](https://github.com/spring-projects/spring-data-envers/pull/195) where the `DefaultRevisionMetadata` is complemented with the `RevisionType` ([here](https://github.com/spring-projects/spring-data-envers/pull/195/commits/e9ca2ef92ebf3948d866e8b4f895b4ac72a1dab0#diff-4085c16e1d58dc649b7ea123b3cbcf59R217)). The same can be done for `AnnotationRevisionMetadata`

**Comment by blaketastic2** [comment]
Any timeframe on getting this merged?

**Comment by bohordo** [comment]
Sup guys, any timeframe on getting this merged?

**Comment by kaikun213** [comment]
Any news when this will be merged?

**Comment by SBylemans** [comment]
I've added it but need tests according to the Spring code of conduct for submitting a pull request.

**Comment by schauder** [comment]
@SBylemans  You added what? And you added it where?

**Comment by SBylemans** [comment]
@schauder I added it locally cause it needs testing before pull request, right? I can create a PR with just the code change, but without testing, is that ok?

**Comment by schauder** [comment]
Go ahead make a PR. I'll check if I can add the tests.

**Comment by SBylemans** [comment]
@schauder Done

**Comment by schauder** [comment]
Merged your PR. Thanks.
