### ISSUE TITLE
Order-dependent flaky test QueryDslRepositoryIntegrationTests.testWithRevisions

### ISSUE THREAD

**Issue by OrDTesters** [spring-projects/spring-data-envers#225]
Currently, test `QueryDslRepositoryIntegrationTests.testWithRevisions` fails when run right after another test, `RepositoryIntegrationTests.testLifeCycle`. The reason is that `RepositoryIntegrationTests.testLifeCycle` saves a new license, but does not delete the license, leading to the later test `QueryDslRepositoryIntegrationTests.testWithRevisions` to fail.

**Comment by schauder** [comment]
Fixed.
