### ISSUE TITLE
org.hibernate.LazyInitializationException: could not initialize proxy - the owning Session was closed

### ISSUE THREAD

**Issue by abid-khan** [spring-projects/spring-data-envers#23]
This exception is thrown when audited entry contains @ManyToOne relationship.

Assume below entity

``` java
@Audited
@Entity
@Table(name = "user")
public class User  {

         ....

    @Audited
    @NotFound(action = NotFoundAction.IGNORE)
    @ManyToOne
    protected User lastModifiedBy;

        ...
        ...

}
```

For above entity, revision entry  has value of ID for lastModifiedBy. And if I try to access lastModifiedBy, below exception is thrown.

``` java
Revisions<Integer, User> revisions = userRepository.findRevisions(user
                .getId());
for (Revision<Integer, User> revision : revisions.getContent()) {
       User revisonEntity = revision.getEntity();
       revisonEntity.getLastModifiedBy().getId()
}
```

``` exception
org.hibernate.LazyInitializationException: could not initialize proxy - the owning Session was closed
    at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:168)
    at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:286)
    at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:185)

```

**Comment by deeTEEcee** [comment]
in a different case, i had controller -> service -> DAO object using @Transaction, but the service object class was autowired rather than the interface, so i never saw that @Transaction was not going through the DAO object. (TLDR: didn't know about AOP & non-interface issues)

**Comment by ValentinBossi** [comment]
> As long as the code snippet you showed does not run inside a transaction (`@Transactional`) this is expected behavior. Repository methods close the session/transaction by default. If you want to traverse related entities you either need to create a bigger transaction boundary or eagerly load the related entities.

where can I find the documentation to this statement of "Repository methods close the session/transaction by default." ?

**Comment by schauder** [comment]
The documentation for this is effectively that about [transaction management of Spring Framework](https://docs.spring.io/spring/docs/current/spring-framework-reference/data-access.html#transaction). Repositories are annotated with `@Transactional`. So a transaction starts before and ends after every call to a repository, if you don't specify any other transactions with a larger scope.

**Comment by kaikun213** [comment]
I have a similar problem. Just in my case I am dealing with Graphql Resolvers, which make it difficult to expand the Transactional scope. 

Similar as the author has tried, I have the property of the entity annotated with `@ManyToOne(fetch= FetchType.EAGER)`, shouldn't that load the entity either way and avoid the lazy exception?

**Comment by kaikun213** [comment]
In my case I have to explicitly initialize and unproxy the fields which are annotated with `fetchType=EAGER` in order to prevent the graphql type-matcher to missmatch with the hibernate proxy.

E.g. 

```
    public static <T> T initializeAndUnproxy(T entity) {
        if (entity == null) {
            return null;
        }

        Hibernate.initialize(entity);
        if (entity instanceof HibernateProxy) {
            entity = (T) ((HibernateProxy) entity).getHibernateLazyInitializer()
                    .getImplementation();
        }
        return entity;
    }
```
And within an entity I call it for the required fields:
```
    public void initLazyFields() {
        super.initLazyFields();
        setBar(initializeAndUnproxy(getBar()));
    }
```

During the regular spring-data queries this fields are initialized by default and not only proxied. What am I missing?
