### ISSUE TITLE
Dependency injection inside RevisionListener stopped working with spring boot 2.3.x

### ISSUE THREAD

**Issue by RodrigoPetter** [spring-projects/spring-data-envers#249]
Here is a sample project about this problem: https://github.com/RodrigoPetter/sample-envers-dependency-injection-problem

My application does not start correctly. It gets stuck right after mentioning the envers in the logs.

> com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
> com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
> org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL8Dialect
> o.h.e.boot.internal.EnversServiceImpl    : Envers integration enabled? : true

If I start the application in debug mode, these are the last lines of logs before it gets stuck:

> o.hibernate.cfg.AbstractPropertyHolder   : Attempting to locate auto-apply AttributeConverter for property [com.example.demo.Revinfo:timestamp]
> o.h.cfg.annotations.SimpleValueBinder    : building SimpleValue for timestamp
> o.h.cfg.annotations.PropertyBinder       : Building property timestamp
> o.h.cfg.annotations.SimpleValueBinder    : Starting fillSimpleValue for id
> o.h.cfg.annotations.SimpleValueBinder    : Starting fillSimpleValue for value
> o.h.cfg.annotations.SimpleValueBinder    : Starting fillSimpleValue for id
> o.h.cfg.annotations.SimpleValueBinder    : Starting fillSimpleValue for timestamp
> org.hibernate.mapping.PrimaryKey         : Forcing column [id] to be non-null as it is part of the primary key for table [my_entity]
> org.hibernate.mapping.PrimaryKey         : Forcing column [id] to be non-null as it is part of the primary key for table [revinfo]
> o.h.boot.internal.ClassLoaderAccessImpl  : Not known whether passed class name [com.example.demo.Revinfo] is safe
> o.h.boot.internal.ClassLoaderAccessImpl  : No temp ClassLoader provided; using live ClassLoader for loading potentially unsafe class : com.example.demo.Revinfo

This problem only happens using version 2.3.x or 2.4 (snapshot). If I downgrade to version 2.2.x everything works as expected.

By doing a little debugging, I managed to find the cause. When I use dependency injection within my `RevisionListener` implementation, this behavior occurs. If I remove the [lines 8-13](https://github.com/RodrigoPetter/sample-envers-dependency-injection-problem/blob/e51f71e17428634a4cff0fe2a24721779f0975b7/src/main/java/com/example/demo/RevisionEntityListener.java#L8), removing the dependency injection, my application starts to work.

I have several Spring Boot applications and this happened to almost all of them when upgrading to version 2.3. The strangest part is that this behavior did not happen in those that had an implementation of `SchedulingConfigurer`.

For example, if the following class is added to the sample project that I mentioned at the top of this issue, the problem stops happening:

```
@Configuration
@EnableScheduling
public class ContextSchedulingConfiguration implements SchedulingConfigurer {

    @Override
    public void configureTasks(ScheduledTaskRegistrar taskRegistrar) {
        taskRegistrar.setScheduler(taskExecutor());
    }
    @Bean
    public Executor taskExecutor() {
        return Executors.newSingleThreadScheduledExecutor();
    }

}
```

Could anyone confirm if this is a bug related to envers or spring? 
I'm sorry if I opened this issue in the wrong project.

**Comment by RodrigoPetter** [comment]
Annotating the `RevisionListener` implementation with `@Service` or `@Component` solved the problem. This probably caused the order of creation of the beans to be done correctly, similar to what should be happening when adding an implementation of `SchedulingConfigurer` as I reported earlier.

**Comment by RodrigoPetter** [comment]
I managed to get around this problem by avoiding using Spring automatic dependency injection and getting the singleton manually from the context:

```java
public class RevisionEntityListener implements RevisionListener, ApplicationContextAware {

    private MyService myService;

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        this.myService = applicationContext.getBean("myService", MyService.class);
    }

    @Override
    public void newRevision(Object revisionEntity) {
        Revinfo revinfo = (Revinfo) revisionEntity;
    }

}
```

**Comment by wimdeblauwe** [comment]
I just tried with `ApplicationContextAware`, but that does not seem to work (Using Spring Boot 2.3.9). If I put breakpoint in `setApplicationContext`, it is called, but then it seems when the RevisionListener does the actual work, it is a different instance where `setApplicationContext` was never called.

**Comment by mp911de** [comment]
`RevisionListener` isn't something that Spring manages. It's a functionality from `org.hibernate.envers.RevisionEntity`. Since Spring Framework 5.1, Spring provides a `SpringBeanContainer` to allow Hibernate bean lookups from the Spring Context. I think this issue requires further investigation on what's broken.

**Comment by mp911de** [comment]
Interestingly, annotating a revision listener with a stereotype annotation such as `@Service` creates multiple instances whereas leaving the listener without an annotation shows the correct behavior. @wimdeblauwe I suggest reporting that behavior against Spring Framework as `SpringBeanContainer` is a framework class.

**Comment by wimdeblauwe** [comment]
Sorry, forget my comment. Using `ApplicationContextAware` on the `RevisionListener` does the correct thing using Spring Boot 2.3.9. I just did not have the correct bean I wanted to take from the context in my unit test I was running. When I fixed that, I am able to take my bean from the context and use it in the listener.

**Comment by mp911de** [comment]
FTR, the way how Envers (Hibernate) requests a bean from the context pretty much controls the behavior you experience. Disabling cached bean access or requiring JPA-compliant lifecycles may cause new instance creation as per https://github.com/hibernate/hibernate-orm/blob/e76241a3091078713dd4b57de085f5fadce5e0db/hibernate-core/src/main/java/org/hibernate/resource/beans/container/spi/BeanContainer.java#L19-L20
