### ISSUE TITLE
Only the most recent change gets recorded in the audit table

### ISSUE THREAD

**Issue by manish-in-java** [spring-projects/spring-data-envers#26]
I have an existing Spring Data annotated entity called `Person`.  I now want to add an entity called `Registration` to the system, with a many-to-many mapping between `Person` and `Registration` through a join table called `PersonRegistration`.  Data in the `Registration` table will be pre-populated and will never be changed from the application.

My requirement is to be able to audit all changes to records in the `PersonRegistration` table.  I added `spring-data-envers` dependency to my project POM, made necessary changes to the Spring configuration and annotations and ran a test case.  I am finding that the audit table for `PersonRegistration` stores only the current state of the records in the `PersonRegistration` table.  It is not storing the history.  A complete sample project is available on [Github](https://github.com/manish-in-java/spring-jpa-envers) to see the problem in action.

Download the sample project and run `mvn clean test`.  The tests will run and generate an H2 database file called `audit.h2.db` in the base folder.  If you open this database using H2 console, you will see equal number of records in `PersonRegistration` and its associated audit table, although the tests have updated the data multiple times.

Is this the expected behaviour?  How can I achieve the required behaviour of saving the complete history for `PersonRegistration` records?

**Comment by scav** [comment]
The only thing that really jumps at me here, is that you have no @-Audited annotation on your  @-MappedSuperclass. We found that this was necessary to be able to get auditing features for classes implementing our abstract entity classes.

As a note, you may want to test this as well:
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED) should probably be moved to the actual entity you do not want to audit, not the relation in PersonRegistration.

If this does not help,  I'm sorry, but that is how we used it, and it works.

**Comment by manish-in-java** [comment]
No, those two did not solve the problem.  I didn't see how adding an `@Audited` to the `@MappedSuperclass` would help since the audit table `PersonRegistrationAudit` is getting generated and also being populated.  Having made the change to the application and running it confirmed that it does not help.

Moving the `NOT_AUDITED` to the actual entities created audit tables and entries from them as well.

**Comment by schauder** [comment]
Your test runs in a single transaction, so as far as Hibernate is concerned there is only a single state involved. If you want to see multiple records you'll need multiple commits.
