### ISSUE TITLE
Reference documentation is missing

### ISSUE THREAD

**Issue by trettstadtnlb** [spring-projects/spring-data-envers#284]
The reference documentation is missing in the official Spring Data documentation: https://docs.spring.io/spring-data/envers/docs/2.4.5/reference/html/#reference

**Comment by schauder** [comment]
This is a duplicate of #61

**Comment by scordio** [comment]
@trettstadtnlb I can imagine the documentation will be available starting from the next release, as it was introduced [after version 2.4.5](https://github.com/spring-projects/spring-data-envers/compare/2.4.5...master) with 0e74d3e9c33a4797e487b2456a380b78cbdca4b5.

**Comment by trettstadtnlb** [comment]
Ok, thanks! I think I only searched open issues before and therefore did not find that one.
