### ISSUE TITLE
Add LICENSE file on the repository

### ISSUE THREAD

**Issue by GonMMarques** [spring-projects/spring-data-envers#295]
Hello, 

I have a question/inquiry, I know that the project is released under the Apache 2.0 license as it is explicitly stated, however, I was wondering can the LICENSE.txt or LICENSE.md be added to the repo? 
I think that could be nice to have because
-  GitHub pickups automatically the license file and adds on the "About" section the license being detected (see https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) 
- GitHub also encourages it: 
> As a best practice, we encourage you to include the license file with your project.
- Not only that, but a lot of Spring projects also do that, example: https://github.com/spring-projects/spring-data-neo4j/blob/master/LICENSE.txt
- Finally, third-party software that tracks component's licenses use the LICENSE.txt file directly to detect and alert if people are using software with no license at all or unknown licenses. Without such file it generates false positives due to the "apparent absence of license"

Thanks in advance.

**Comment by mp911de** [comment]
Currently, the license file is located at src/main/resources (src/main/resources/license.txt). I think it makes sense to put it also in a location, where GitHub can identify it.

**Comment by GonMMarques** [comment]
> Currently, the license file is located at src/main/resources (src/main/resources/license.txt). I think it makes sense to put it also in a location, where GitHub can identify it.

Great, so maybe under the source directory? Do you want me to open a PR? Thanks for the fast feedback

**Comment by mp911de** [comment]
Let me take this topic to the team as we have 18 Spring Data repositories and such a change should go coordinated into all repos.

**Comment by gregturn** [comment]
We'll ensure that a LICENSE file is put at the root of all the modules.

**Comment by GonMMarques** [comment]
Thank you both @gregturn @mp911de

**Comment by gregturn** [comment]
I've actually added `LICENSE.txt` files to this as well as all the other Spring Data modules (albeit through different tickets).

See https://github.com/spring-projects/spring-data-envers/commit/2db3bc30b33219d650c75a64e916a90ee74ccdbe.
