### ISSUE TITLE
Spring-data-envers incompatible with QueryDSL

### ISSUE THREAD

**Issue by sdoxsee** [spring-projects/spring-data-envers#30]
I'm creating a github ticket for this old issue as I don't think it has been resolved. https://jira.spring.io/browse/DATAJPA-387 or
http://forum.springsource.org/showthread.php?129116-Repository-extending-spring-data-envers-and-querydsl

**Comment by juvs** [comment]
Agree, the issue persist!

**Comment by httpants** [comment]
I've hit this issue as well.  Need a workaround or a fix.

**Comment by MathieuClusiau** [comment]
Me too, I need a workaround or a fix.

**Comment by wramirez2401** [comment]
Me too.

**Comment by Marche86** [comment]
Me too, I need a workaround or a fix.

**Comment by tanapoln** [comment]
Hi all, I just facing this problem. For the workaround, I have to create custom implementations of `EnversQueryDslJpaRepository` and `EnversRevisionQueryDslRepositoryFactoryBean`.
All you need to do is copy and paste all code and change the extends from `SimpleJpaRepository` to `QueryDslJpaRepository` and add some constructor. Please find gist below:

https://gist.github.com/tanapoln/af4b4a40e5472f0c8e9625d31f7d2153

I don't know whether it is good enough or do I miss something. It just work for me now.

**Comment by nbrooks** [comment]
I'm having this issue as well. The workaround posted by @tanapoln seems to work so far. In addition to adding the two specified classes to the classpath, I updated the `@EnableJpaRepositories` annotation with `repositoryFactoryBeanClass = EnversRevisionQueryDslRepositoryFactoryBean.class`.

**Comment by philippeboyd** [comment]
I got the same issue and came across this which fixed my build problem
https://github.com/querydsl/querydsl/issues/239

**Comment by lanmolsz** [comment]
Me too, I need a workaround or a fix.

**Comment by schauder** [comment]
This is actually fixed.
