### ISSUE TITLE
Release 2.5.3 (2021.0.3)

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-envers#303]

**Comment by nictas** [comment]
Will the update to Hibernate Envers 5.5.3 be included in this release? Also, is there any estimation on when this task will be completed?

**Comment by schauder** [comment]
The Envers upgrade is not planned to be included in this release, so far.

This release is scheduled for end of the week.

Of course you can always just pick your preferred version of Envers, especially since the move to 5.5.3 didn't require any other change so far.
