### ISSUE TITLE
Roadmap of Spring Data Envers

### ISSUE THREAD

**Issue by cklee75** [spring-projects/spring-data-envers#33]
Hi Project Owner,

Would like to check the roadmap of this project. When M, RC and GA release will be ready?

Thanks.

**Comment by olivergierke** [comment]
See the [issue tracker](https://github.com/spring-projects/spring-data-envers/milestones). As we're currently in 0.x phase there are no milestones, release candidates and whatever. We try to follow the Spring Data release trains and perform a release with every GA version of that but be aware that this is currently no project of high priority, not included in the train etc.

**Comment by zampettim** [comment]
So @olivergierke, what is needed to start getting this project including in the Spring Data Release Trains and to a 1.x level?

**Comment by olivergierke** [comment]
Resolved, as Spring Data Envers is now part of the Spring Data release train.
