### ISSUE TITLE
EnversRevisionRepositoryImpl Issue

### ISSUE THREAD

**Issue by gruberasheridc** [spring-projects/spring-data-envers#34]
Hi,

I'm encountering an issue when using the findRevisions(ID id, Pageable pageable) method in a specific case.
I have two entities with a OneToOne relationship. Flow:
1. Created both entities and one revision is created in the revinfo table.
2. Edit the non-owner entity and an new revision is created only for that entity.
3. Call the findRevisions with the ID of the non-owner entity.
4. The issue occurs within the getEntitiesForRevisions private method. When fetching the revisionEntities map (Map<Number, Object> revisionEntities), the first revision information entity is returned lazy and therefore its key in the map is zero. The "real" entities' (non-owner) revision information is returned correctly. Then, when the toRevisions private method is called the entities' revision entity is not found in the map and an exception if thrown.

I encounter the issue only when the non-owner entity is edited for the first time after creation.  Any suggestion?

Thanks.

**Comment by schauder** [comment]
Sorry for the late reaction. 
Could you provide an example repository reproducing this issue?

**Comment by abobrov-clgx** [comment]
I have the same issue. Example is here: https://github.com/aquariusmaster/spring-data-envers-bug

**Comment by schauder** [comment]
@abobrov-clgx Thanks for providing a reproducer.

**Comment by abobrov-clgx** [comment]
Hi @schauder, any updates?

**Comment by schauder** [comment]
Updating to boot version 2.3.1.RELEASE seems to solve the problem.

Can you confirm this?

**Comment by abobrov-clgx** [comment]
Hi, @schauder 
Yes I confirm it works.
Thanks)

**Comment by schauder** [comment]
Thanks for the confirmation.
