### ISSUE TITLE
Selecting all revisions for type regardless of ID

### ISSUE THREAD

**Issue by kzander91** [spring-projects/spring-data-envers#353]
I have the requirement to display a report of everything that happened to a _table_ (all inserts, updates, deletes), not just to a particular record within that table.

The `RevisionRepository` methods only support querying for the revisions by `ID`, but I need all revisions across all entities.
A (slow) workaround is selecting all my entities, iterating over them and performing `findRevisions(id)` for each one, but that won't give me the revisions for entities that have already been deleted.

Could you add `findAllRevisions(Pageable)` and `findAllRevisions()` methods to `RevisionRepository`?

Looking at `EnversRevisionRepositoryImpl`, the `createBaseQuery` method should probably be adjusted to _not_ add the `AuditEntity.id().eq(id)` condition when called from these new `findAll` methods.

I tried creating a custom subinterface extending `RevisionRepository` and implementing the method myself, but that didn't really work generically, probably due to #192.

**Comment by gomezAlvaro** [comment]
I had exactly the same issue - I ended up doing a query retrieving the id of all the items in the audit table and then executing ```findRevisions(id)``` but in the end it's not a very nice workaround. I would really appreciate having the methods you suggested in the ```RevisionRepository```.

**Comment by schauder** [comment]
https://github.com/spring-projects/spring-data-jpa/issues/2481 is the same issue and since SD Envers is getting moved into the SD JPA repository we'll keep that issue and close this one as a duplicate although it is the older one.
