### ISSUE TITLE
EnversRevisionRepositoryFactoryBean doesn't use custom RevisionEntity

### ISSUE THREAD

**Issue by raoulk** [spring-projects/spring-data-envers#4]
I use a custom `RevisionEntity` with `@RevisionNumber` of type `Long` (instead of `Integer`).
The creation of my repository

``` java
public interface CustomerRepository extends RevisionRepository<Customer, UUID, Long>
```

fails:

```
java.lang.IllegalStateException: Configured a revision entity type of interface com.test.CustomerRepository with a revision type of class java.lang.Integer but the repository interface is typed to a revision type of class java.lang.Long!
```

in line 121 of the `EnversRevisionRepositoryFactoryBean`. Debugging showed me that the `revisionEntityInformation` attribute contains a `DefaultRevisionEntityInformation` object. I would expect a `ReflectionRevisionEntityInformation` object that contains information about my custom `RevisionEntity`. My `RevisionEntity` looks like this:

``` java
@Entity
@RevisionEntity
@SequenceGenerator(name = "REVISION_SEQ", sequenceName = "revision_seq")
public class RevEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "REVISION_SEQ")
    @RevisionNumber
    public Long id;

    @RevisionTimestamp
    public Long timestamp;

    @Transient
    public Date getRevisionDate() {
        return new Date(getTimestamp());
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }
}
```

**Comment by scordio** [comment]
> We'll probably add a custom `<envers:repositories />` element to the Spring Data Envers project that will expose the revision entity class attribute directly to ease the setup.

Hi @odrotbohm, I couldn't find anything about it so I guess this was never added. Is it something you would still consider or is subclassing the preferred approach?

**Comment by odrotbohm** [comment]
We have no plans to extend our XML based configurations at the moment.

**Comment by scordio** [comment]
Thanks for the fast feedback!

What about something for Java config? I could imagine a custom annotation to avoid the `EnversRevisionRepositoryFactoryBean` custom class wired into `@EnableJpaRepositories`.

**Comment by odrotbohm** [comment]
We just created #289.
