### ISSUE TITLE
Include Revision Type in Revision

### ISSUE THREAD

**Issue by SingleShot** [spring-projects/spring-data-envers#47]
As a user of the revision repository interface
I want to see the type of revision
So that I can act upon whether the revision was an insertion, update, or deletion.

**Comment by gigaga** [comment]
Hi,
Same need !( How to do that?

**Comment by jktaylor21** [comment]
I would love to be able to do that from within spring data envers as well. As it stands right now, I will need to write my own AuditQuery and interrogate the results to get the revision type.

**Comment by drenda** [comment]
Hi, any news about this? I am wondering why the revtype is not present in Spring Data envers. I mean, it's very important understand if the revision refers to a add, change or delete. Whithout that basically it's needed to access to Envers directly. I bet there is a reason of this choice but I don't understand which is. Is there someone can explain the reason of this? 

Thanks

**Comment by essentinal** [comment]
Unfortunately the AuditReader does not provide access to the RevisionType, so it seems to be a general Envers issue and not one of this project.

**Comment by ytvnr** [comment]
AuditReader provide the RevisionType through forRevisionsOfEntity method, for example:
```java
auditReader
       .createQuery()
       .forRevisionsOfEntity(MyEntity.class, false, true)
       .getSingleResult());
```

It returns an array of 3 objects, the third is the RevisionType.
So I think it is possible.

@spring-issuemaster, this issue is opened since 2016, can you take a look at this please ?
Thanks
