### ISSUE TITLE
Add support for sorting revisions by revision number in paginated access

### ISSUE THREAD

**Issue by daoudimed1505** [spring-projects/spring-data-envers#55]
Hi 
How to sort revisions by the latest date 
I tried this 
`PageRequest request = new PageRequest(numberPage-1, PAGE_SIZE, Sort.Direction.DESC, "revisionNumber" );`

 but it s not working, I'm i doing smth wrong in here ?
Thanks

**Comment by olivergierke** [comment]
What code are you executing exactly? What results do you see? What do you expect to see?

**Comment by daoudimed1505** [comment]
I'm trying to get the history of the modifications of an entity, and i want to view the list of these modifications by the modification date of revision (the entity here is "revision") (DESC or ASC) , the code i m running : 
`public Page<Revision<Integer, DossierMedical>> getAllRevisionsPage(Integer id, Integer numberPage) {
		// TODO Auto-generated method stub
		PageRequest request = new PageRequest(numberPage-1, PAGE_SIZE, Sort.Direction.DESC, "revisionNumber" );
		return dossierMedDao.findRevisions(id, request);
	}`
I used the "revisionNumber", REV and timestamp as the Sort parametre and i get nothing, it s sorted by default.

**Comment by daoudimed1505** [comment]
to summarize
I juste want to get allRevisions sorted by the latest date of revision

**Comment by olivergierke** [comment]
Two things: it looks like the Envers API doesn't support any dedicated sorting, which means we can't influence the order in which results are returned in the first place. Also, by default, the `Revisions` are sorted ascending, which means you get the oldest elements first. We're currently not inspecting the sort property at all (mostly due to the first aspect mentioned). However, we could provide a dedicated `Sort` implementation that basically indicates a request for the alternate order (latest revisions first).

**Comment by olivergierke** [comment]
I've filed a [ticket](https://jira.spring.io/browse/DATACMNS-888) in the upstream project to get the necessary infrastructure in place. Don't think we're gonna get this into Ingalls M1 as it's right around the corner.

**Comment by daoudimed1505** [comment]
Okay, I understand ,Thank you very mush Mr.Oliver for your explanation and your time.

**Comment by pranavansiva30** [comment]
you can get Revision by RevisionNumber ASC or DESC.
You have to create Sort object using ,RevisionSort calss(RevisionSort.asc() or RevisionSort.desc())

example:
int index=0;
int itemPerPage=10;

Pageable pageable=PageRequest.of(index,itemPerPage,RevisionSort.asc());

Page<Revision<Integer, User>> userRevisions = userRepository.findRevisions(Long userId,pageable);

**Comment by schauder** [comment]
Hi @pranavansiva30,

I'm not sure what the intent is behind this comment. 
Do you expect us to do anything?
