### ISSUE TITLE
Spring Data Envers Documentation Only Contains General Spring Data Information

### ISSUE THREAD

**Issue by nbrooks** [spring-projects/spring-data-envers#61]
The Spring Data Envers [Documentation Link](http://docs.spring.io/spring-data/envers/docs/current/reference/html/) in the README file appears to be showing only the general Spring Data Commons information, and no specific details about working with spring-data-envers. The sections are all related to general CrudRepository usage, and 'Envers' only appears in the page header ('revision' doesn't appear anywhere in that document). This is also an issue for older versions of the documentation. I'm assuming that the links are just referring to the wrong documents somehow, so hopefully this is an easy fix. Apologies if this isn't the correct place to submit this feedback.

**Comment by kalexmills** [comment]
It has been three years, and the documentation is still non-existent. Why is this project still part of the spring framework?

**Comment by scordio** [comment]
I am happy to help to improve the docs if needed.

**Comment by schauder** [comment]
@scordio Help is always welcome.

**Comment by scordio** [comment]
@schauder may I ask for some pointers about the documentation source files? https://github.com/spring-projects/spring-data-envers/tree/master/src/main/asciidoc seems to be empty so I'm wondering where they are actually stored.

**Comment by schauder** [comment]
@scordio Sure.

https://github.com/spring-projects/spring-data-envers/tree/master/src/main/asciidoc isn't empty, there is an `index.adoc` which is the correct place to start. 

We typically create a separate file for the main documentation which then gets included. The canonical name would be `envers.adoc` in the same directory.

You might want to take a look in the corresponding source files in other projects, for example Spring Data JDBC https://github.com/spring-projects/spring-data-jdbc/tree/master/src/main/asciidoc

**Comment by scordio** [comment]
Thanks and sorry, I thought I opened that file :facepalm:
