### ISSUE TITLE
Write the audit records to another datasource

### ISSUE THREAD

**Issue by WThamira** [spring-projects/spring-data-envers#69]
@olivergierke can we store audit data in separate database instead of  main database?

**Comment by olivergierke** [comment]
I guess that's something to lookup in the Envers documentation. Spring Data Envers only provides a repository abstraction on top of it.

**Comment by Naros** [comment]
@WThamira You can specific an Envers default schema or catalog setting as part of the configuration properties and Envers will generate its schema exports based on those provided values.  Just be sure based on the dialect you're using that you provide the appropriate value for those settings as some dialects support one or the other.
