### ISSUE TITLE
JDBC Syntax exception

### ISSUE THREAD

**Issue by Michal-Hanak** [spring-projects/spring-data-envers#7]
Please check class
org.springframework.data.envers.repository.support.EnversRevisionRepositoryImpl
and function "Page findRevisions(ID id, Pageable pageable)". Missing revisionNumbers.isEmpty() condition! It throws JDBC SQL syntax error.

Otherwise nice job ;-)

**Comment by stuemke** [comment]
Hi,
I also ran into that issue with a wrong MySQL syntax:

>  com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1

In my case I have an existing database filled with entities. I tried to enable envers auditoring for that application. When starting from scratch with a clean database I do not have any issues, but when migrating with existing data I get this issue. 

I debugged until I got to org.hibernate.envers.internal.reader.AuditReaderImpl.findRevisions(Class<T> revisionEntityClass, Set<Number> revisions) called by the class and method mentioned by  @Michal-Hanak with an empty set of revision numbers. The exception is thrown when the method tries to get the result list from the query.

I have a MySQL 5.6.31 Database my application uses the mysql connector 5.1.26.

**Comment by olivergierke** [comment]
Generally speaking, all SQL creation is done by HIbernate Envers or Hiberante in particular. That means, if you run into errors with the SQL created for your database vendor, please file an issue with Hibernate.

**Comment by stuemke** [comment]
Hello Mr. Gierke,

thanks for the quick answer. I will raise an issue with Hibernate if there isn't already one for it. Maybe you should close this issue because it is not to be fixed in spring-data-envers. 

Regards
Claus

**Comment by stuemke** [comment]
Just to complete the discussion. I've found a ticket at Hibernate for this issue:
[HHH-8091: Hibernate produces SQL - "in ()" - which is invalid in at least Oracle, MySQL and Postgres](https://hibernate.atlassian.net/browse/HHH-8091)

**Comment by schauder** [comment]
Closing, because it is a Hibernate issue, not a Spring Data issue.
