### ISSUE TITLE
How customize Revision

### ISSUE THREAD

**Issue by drenda** [spring-projects/spring-data-envers#87]
According to https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#_basics (21.5. Revision Log) it's possible customize RevisionEntity to store additional data in each revision like the user made the change (it's very useful!).

Is there a way to customize Revision in order to retrieve additional information?

**Comment by schieck0** [comment]
Use `(MyCustomRevisionEntity) revision.getMetadata()`

**Comment by drenda** [comment]
Thanks @schieck0
