### ISSUE TITLE
Could findRevisions(id,pg) pageable support Sort?

### ISSUE THREAD

**Issue by mikesenecal** [spring-projects/spring-data-envers#9]
In `EnversRevisionRepositoryImpl`, how would user pass in the sort direction to paginate from latest to earliest revision? Default seems to be ascending. Unless im missing what property to pass in to get the Sort.Direction.DESC, "?" ?

**Comment by kernicke** [comment]
is there any chance that this feature will be merged into a future version? Our customer really likes the ability to view the history of entities, but he would like to see the newest first. Its hard to explain to him, why we cannot sort it like we want.

**Comment by madness-inc** [comment]
See #55  -> [DATACMNS-888](https://jira.spring.io/browse/DATACMNS-888) which is fixed in 1.13 RC1

**Comment by drenda** [comment]
Whatch out the property name must be `__revisionNumber__` otherwise the default sorting is ASC.

**Comment by schauder** [comment]
This is solved by #55 as hinted to by @madness-inc
