### ISSUE TITLE
Is this repo still maintained, apart from version?

### ISSUE THREAD

**Issue by klchankalam** [spring-projects/spring-data-envers#93]
Since last year, it seems like version were raised without other fix.

I am using it in multiple projects and the following concerns me:

1.Reference document is spring data repo general one, not spring data envers
Not envers specific -> https://docs.spring.io/spring-data/envers/docs/1.1.6.RELEASE/reference/html/
The issue had been open for 10 months -> https://github.com/spring-projects/spring-data-envers/issues/61

2. Pull requests are not merged. One of the example(that I workaround in my own code as not merged):
https://github.com/spring-projects/spring-data-envers/pull/45

So, is this repo still maintained? Or if Spring is not going to support this anymore, can we have the timeline for it so that we can migrate away?

**Comment by heruan** [comment]
Also, Envers version is pretty old and does not support Hibernate ORM 5.2 (which is the current version used by Spring).

**Comment by schauder** [comment]
Yes, this project is still maintained. I'll try to put some time into it in the not too far future.
